export default () => ({
  mailchimp_id: "",
  idMailchimpMember: "",
  email_address: "",
  full_name: "",
  web_id: 0,
  email_type: "",
  status: "",
  merge_fields: {},
  interests: {},
  stats: {},
  ip_signup: "",
  timestamp_signup: "",
  ip_opt: "",
  timestamp_opt: "",
  member_rating: 0,
  last_changed: "",
  language: "",
  vip: false,
  email_client: "",
  location: {},
  source: "",
  tags_count: 0,
  tags: [],
  list_id: "",
  _links: [],
});
